import 'package:jhandgaon_guide/guide/campaign_data.dart';

class Guide {
  static String IMPROV_FANTASY_INTRO =
      'Improv fantasy is genre of Role-Playing Game (RPG) that focuses on collaborative story-telling via assumption of fictional characters in fictional settings.\n\nTo put it simply: it’s like you and your friends are characters in a movie but instead of being passive observers it is the players who move the characters and plot of the movie forward.\n\nIn improv fantasy, you use your chosen character to enact actions you think they would make and enact them out as such. Actions that have a luck or probability based outcome will prompt your Director to request a dice roll. The condition of the dice roll will be pre-informed.\n\nYour actions are limitless, and can go as far as your Director allows.\n\nHow to play?\n1. Director gives basic premise of game & mechanics\n2. Characters are chosen and defined\n3.Director begins with setting\n4.Improv your way through!\n\nRemember to be respectful yet also have fun.';
  static String INTRO_TEXT =
      'The small-town crime drama has been the most popular genre to come out of modern Indian pop culture - the most driect point of it\'s ascent being Gangs of Wasseypur, while the roots trace back further to the 90s cult reign of Mumbai crime movies like Satya, Vastav, Rangeela, etc. where Ram Gopal Verma and Sanjay Dutt were the placeholders of what Anurag Kashyap and Nawazuddin Siddiqui occupy today in our pop culture. \n\nA certain fascination for this genre has gripped the nation and content in this genre has been boiled down to the formula by OTT platforms to guarantee a sure shot hit. \n\nJhandgaon is just one more gaon in the ever expanding Indian Crime Town Cinematic Universe. The difference here is that you get to live Jhandgaon in its full glory, not just watch it. The rival gangs, police love interests, smugglers, dacoits, beggars, innocent citizens are all you and your real life friends. \n\nSabka badla lega tera Faizal or what if Faizal says fuck it to the generational feud and becomes a cop? \n\nJamtara is the cyber crime capital of India, but you and your gang can make it the cyber crime capital of the world. Or will the cops outsmart you?\n\nAs syndicate head Pushpa, you expand into smuggling beyond red sandalwood to become the Pablo Escobar of India or quit smuggling chase political aspirations and become the Prime Minister.\n\nThe posibilites are endless!';
  static String POSTER_IMAGES = 'assets/images/posters.png';
  static String JHANDGAON_RPG_INTRO =
      'Jhandgaon is small town in India, in the state of Uttarajhand. A gritty place where power prevails over peace - survivalism is the only constant here.\n\nPlaying Jhandgaon is all about living, dominating, exploring, avenging, or just doing pure bakchodi. The objective is yours.\n\nPick your unique character, pick a campaign, and prepare for chaos!\n\nThe rival gangs, police, love interests, smugglers, dacoits, beggars, innocent citizens are all you and your fellow players.';
  static String JHANDGAON_IMAGE = 'assets/images/jhandgaonmarket.png';

  static Map<String, String> playerManifesto = {
    'Communicate':
        'Before deciding to play, communicate what kind of game you are expecting - is it more action oriented or just something light and fun? Also communicate practical things like your time availability.\n\nIf at any point something or someone in the game makes you feel uncomfortable, do speak up. A safe space is key to a good game for everybody involved.\n\nGood communication shouldn\'t also be limited to the negative. If there is something that improved your gameplay experience then make sure to mention it at the end of the game.Good communication shouldn\'t also be limited to the negative. If there is something that improved your gameplay experience then make sure to mention it at the end of the game.\n\nA big part of improv fantasy is collaborative story-telling, so occasionally the members of the group need to discuss what\'s going on as co-authors of the story rather than players of the game.',
    'It Won\'t Always Go How You Like':
        'There are a lot of different playing styles and game styles out there. If you\'re looking for a something with exploration and character development but join a game that\'s more action-oriented and with fighting - you most likely won\'t enjoy yourself. Communicate with the group (see previous point) to prevent this from happening.\n\nYou can either adjust your expectations and play something different. You can have the Director set the game according to what you want, if everybody is on board. Or you can also leave the game. But always remember that you can\'t expect people to sacrifice their enjoyment so you can play the game according to your benefit.\n\nThere will be plenty of chances to play the campaigns you like in life!',
    'Respect the Other Players\' Time':
        'Make sure you arrive in time & have made space to play with minimal interruptions.\n\nIf you can\'t make it or are going to be late, let the others know as soon as possible so they can adjust their plans accordingly.\n\nIf you are late or can\'t make it, and your character is important to the current story or the gaming group is small - the other players might prefer to postpone or delay the game until everyone can show up. Or alternately, they can request the Director to control your character to move ahead the plot, with your consent, of course.\n\nEverybody has busy lives and they\'ve all chosen to eke out time from their lives to dedicate it to playing their chosen game, just make sure not to waste anybody\'s time.',
    'Be an Active Player':
        'Improv fantasy games don\'t have a script and rely on the Director & characters to move ahead the story line. Being active extends beyond making your character do things.\n\nYou have a chance to help shape the world and the story by introducing supporting characters, pursuing character goals outside of the main story, and helping the Director set the scene and describe the world.\n\nWhen you\'re playing, always be on the lookout for ways to make your character and the world around more interesting. Let your imagination run wild.\n\nIf you have an idea, put it out there. The worst thing that can happen is that the Director will say "No".',
    'Share the Spotlight':
        'While a lot of times you will be playing a hero/villain/key character, you have to remember that though this is a movie - you aren\'t the only star. Improv games are more like a movie with an ensemble cast.\n\nSometimes the focus will be on you & your actions, and sometimes it won\'t. When the spotlight isn\'t on you - remember to be a good support. Start in-character conversations, come up with plans that make use of others\' special skills, contribute to others\' plans, help them achieve their objectives.',
    'The Show Must Go On':
        'Even though moving the game ahead is the Director\'s responsibilty, a game can still stall for many reasons. Make sure you are moving the game ahead and not getting stuck on obvious dead-ends. If you feel like somebody else is holding the game up, then communicate to move ahead. For example, your fellow players could be spending too much time interrogating an NPC when it is clear they don\'t have more information to give. Propose to move ahead in this case and vocalise what you think.',
  };

  static Map<String, String> directorGuidelines = {
    'Setting up':
        'Before deciding to play, communicate with the group what kind of game are they expecting - is it more action oriented or just something light and fun? Also communicate practical things like your time availability.\n\nThis will help you prepare for the mood, tone, and pacing of the game play.',
    'Brief the Players':
        'Let the players know a tentative summary of the game without giving away too much. You can let them also know what setting is being used, and if a particular area of that setting will be in play. Let them also know whether it\'s high/low fantasy, sci-fi etc if they players haven\'t defined this already.\n\nLet them know how long you expect the campaign to run. This is of course tentative but the point is to make sure they have an understanding of what time commitment they are making.\n\nLet them know any exceptions to published game rules beforehand.',
    'Pre-play':
        'Run your players through game mechanics again. Make sure to also establish safe space rules. \n\nAlso set-up the Playmat room before your players come in, to make sure everybody is ready to start playing and also to not waste anybody\'s time.',
    'Characterisation':
        'Let your players pick their characters or build them out themselves. Don\'t go ham on building a plot right now -let the ideas marinate in your head while you wait for your players to turn in their characters. If you want your players to be invested in the campaign, their character backstories need to be woven through the core of the story.\n\nA character\'s story shouldn\'t feel like a side-quest, because it\'s literally the reason they are doing any of this.\n\nA character\'s backstory and individual story arc should be so intrinsic to the plot that the story depends on it for stability. If a character dies midway, don\'t toss out that part of the story. Leave it there.\n\nIf you flesh out your campaign before you know these things, you\'re going to have a harder time weaving them into the fabric of your campaign.',
    'Starting the Campaign':
        'Okay, your players have turned in their characters and backstories and you\'ve got everything you need to start doing the real work of writing for your new campaign. Sketch out the primary conflicts of the core story, the major NPCs and factions that relate to it, and any lore you\'re going to need to communicate to the players very early on in order to give them a chance in hell of figuring out what to do.\n\nWhen it comes to breaking things down in detail, try to contain that to their first small quest (or two if you\'re going to give them the option to choose between a couple). You\'ll need the detail at the beginning to help immerse them into the world, and giving them a few simple choices to make early on will help them ease into their characters and get a feel for how your world works.',
    'Running the Campaign':
        'Remember to not plan your campaign too rigidly. Instead focus on key locations & character traits. You can control the narrative to some extent by inserting critical NPCs, items/clues or offering limited choices to the characters. Example: A forking path in the woods, an NPC that mentions that the weapons the characters need are in a certain location, or a fallen piece of paper or letter that gives an insight into the villain\'s location or the location of the villain\'s love interest.',
    'Making it Fun':
        'A way to make the campaign fun is to control the pacing. If your players are getting stuck on coming to a consensus on actions then bring the resolution to them! This way the campaign doesn\'t go around in the same circles.\n\nAnother interesting thing to do is to pepper the game with inside jokes and funny parallels to the real world. Example: One of the campaigns has a WeWork Jhandgaon as a location! which on introduction itself guarantees a few giggles.',
    'Feed Into The Players':
        'Always follow the improv rules of \'Yes, and…\'\n\nAs a Director, you have the liberty to veto all moves but that\'s not enjoyable to anybody. Remember to play into what the players are doing, and go along with them as much a you can. This is collaborative story-telling, and while the Director is meant to add healthy boundaries for the sake of cohesion - always remember this is fantasy and fantasy is meant to have an element of the impossible & absurd!',
  };
}
